services:
  evewhoswho:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      EVE_SSO_CLIENT_ID: ${EVE_SSO_CLIENT_ID}
      EVE_SSO_CLIENT_SECRET: ${EVE_SSO_CLIENT_SECRET}
      EVE_SSO_CALLBACK_URL: ${EVE_SSO_CALLBACK_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      DATA_DIR: ${DATA_DIR:-/data}
    volumes:
      - ./data:/data
